blueprint:
  name: Smart Modus Control by Room
  description: 1st Convert from OpenHAB light automation to Home Assistant
  domain: automation
  input:
    room_name:
      name: Room Name
      description: Name of the room
      default: Kueche
    smart_mode:
      name: Smart Mode
      description: Smart mode selector (e.g., 'standart', 'automatisch', 'putzen', etc.)
      selector:
        text: {}
    motion_sensor:
      name: Motion Sensor
      description: Motion sensor in the room
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    illuminance_sensor:
      name: Illuminance Sensor
      description: Sensor to measure illuminance
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    main_light:
      name: Main Light
      description: Main light group
      selector:
        entity:
          domain: light
    ambient_light:
      name: Ambient Light
      description: Ambient light group
      selector:
        entity:
          domain: light
    illuminance_threshold:
      name: Illuminance Threshold
      description: Threshold for activating lights
      default: 75
      selector:
        number:
          min: 0
          max: 1000
          step: 1
    timer_duration:
      name: Timer Duration
      description: Timer duration in minutes
      default: 10
      selector:
        number:
          min: 1
          max: 60
          step: 1
    logging:
      name: Enable Logging
      description: Enable debug logs
      default: false
      selector:
        boolean:

variables:
  room: !input room_name
  smart_mode: !input smart_mode
  motion_sensor: !input motion_sensor
  illuminance_sensor: !input illuminance_sensor
  main_light: !input main_light
  ambient_light: !input ambient_light
  illuminance_threshold: !input illuminance_threshold
  timer_duration: !input timer_duration
  logging: !input logging

trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"

condition:
  - condition: numeric_state
    entity_id: !input illuminance_sensor
    below: !input illuminance_threshold

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ smart_mode == 'automatisch' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input main_light
            data:
              brightness_pct: 100
      - conditions:
          - condition: template
            value_template: "{{ smart_mode == 'putzen' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input main_light
            data:
              brightness_pct: 100
  - delay:
      minutes: !input timer_duration
  - service: light.turn_off
    target:
      entity_id: !input main_light

  domain: automation
  input:
    room_name:
      name: Room Name
      description: Name of the room
      default: Kueche
    smart_mode:
      name: Smart Mode
      description: Smart mode selector
      selector:
        input_select.entity_id:
    motion_sensor:
      name: Motion Sensor
      description: Motion sensor in the room
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    illuminance_sensor:
      name: Illuminance Sensor
      description: Sensor to measure illuminance
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    main_light:
      name: Main Light
      description: Main light group
      selector:
        entity:
          domain: light
    ambient_light:
      name: Ambient Light
      description: Ambient light group
      selector:
        entity:
          domain: light
    illuminance_threshold:
      name: Illuminance Threshold
      description: Threshold for activating lights
      default: 75
      selector:
        number:
          min: 0
          max: 1000
          step: 1
    timer_duration:
      name: Timer Duration
      description: Timer duration in minutes
      default: 10
      selector:
        number:
          min: 1
          max: 60
          step: 1
    logging:
      name: Enable Logging
      description: Enable debug logs
      default: false
      selector:
        boolean:

variables:
  room: !input room_name
  smart_mode: !input smart_mode
  motion_sensor: !input motion_sensor
  illuminance_sensor: !input illuminance_sensor
  main_light: !input main_light
  ambient_light: !input ambient_light
  illuminance_threshold: !input illuminance_threshold
  timer_duration: !input timer_duration
  logging: !input logging

trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"

condition:
  - condition: numeric_state
    entity_id: !input illuminance_sensor
    below: !input illuminance_threshold

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input smart_mode
            state: "automatisch"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input main_light
            data:
              brightness_pct: 100
      - conditions:
          - condition: state
            entity_id: !input smart_mode
            state: "putzen"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input main_light
            data:
              brightness_pct: 100
  - delay:
      minutes: !input timer_duration
  - service: light.turn_off
    target:
      entity_id: !input main_light
